### PR TITLE
Adding variables to allow findings to be ignored if required

### PR DESCRIPTION
**Pull request by danderson14**

### CODE REVIEW

**Comment by lfisher47** [comment]
I like the variables, I had actually made some specific ones I had needed so this won't merge cleanly, but I would personally prefer variables that told what it was instead of the number because that involves a lot more lookup instead of understanding what service/package the variable applies to.

**Comment by danderson14** [comment]
I'll swing back around and check out how you've done it when i get some time and possibly refactor my variables to match.  Initial thought on my end was that it would be potentially easier to revisit the settings under an audit situation since the auditors would be referencing them by number though you're right in that it does make it harder to know what the setting actually does when you're looking at changing it

**Comment by danderson14** [comment]
yea looking at what you've changed being for foreman functionality it is the same reason i went down my path.  I'll dump this branch then

**Comment by lfisher47** [comment]
I'm happy to put variables for all the items, instead of just the ones I
needed at the moment.  I just don't actually get STIG audits so using the
numbers is way more complicated.

Plus I've started using SCAP scans since there is a foreman plugin for
them, which may have the references in them, but are more English than
numbers.

**Comment by danderson14** [comment]
sounds good i may go back and add english variables if i feel driven just more a note that my branch's changes aren't even needed for myself when compared to the ones you've made.

**Pull request closed without merging**
